services:
  db:
    image: postgres:15
    container_name: culturo
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: culturo
    ports:
      - '5433:5432'
    volumes:
      - culturo_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: nest_api
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env.dev
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: culturo
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@culturo.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_DEFAULT_LISTEN_PORT=80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - '8081:80'

  vue:
    build:
      context: ../plan-culture-front
      dockerfile: dockerfile
    container_name: vue_app
    ports:
      - '5173:5173'
    volumes:
      - ../plan-culture-front:/app
      - /app/node_modules
    environment:
      NODE_ENV: development

volumes:
  culturo_data:
  pgadmin_data:
